### ISSUE TITLE
NullPointerException in setDisplayHomeAsEnabled

### ISSUE THREAD

**Issue by athasamid** [nileshpambhar/MultiPhotoPicker#2]
error while run this library
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                                                     at com.nileshp.multiphotopicker.photopicker.activity.PickImageActivity.onCreate(PickImageActivity.java:170)
                                                                                     at android.app.Activity.performCreate(Activity.java:6367)

**Comment by MyoZawOo** [comment]
I've got the same error.

**Comment by athasamid** [comment]
@MyoZawOo i fix this issue by change glide version in your app to specific version `3.8.0`
this library use old version of glide

**Comment by sharkboy777** [comment]
This exception occurs when the activity theme is having no actionbar.

the parent theme in <application> tag should have actionbar enabled theme.

like android:theme="@style/AppTheme" or any other theme which have actionbar enabled.....

by default the photopicker activity takes the parent theme. So that theme in application should have actionbar enabled.
